### ISSUE TITLE
Made a pypi release of your repo

### ISSUE THREAD

**Issue by frgfm** [PhilJd/contiguous_pytorch_params#3]
Hey there @PhilJd,

Terrific work with this neat trick :ok_hand: 
I've been using it for a while and it's really helpful. As I have to make a release on another project that depends on your package, a non direct URL dependency is required. So I made a pypi release of your work over here: https://pypi.org/project/contiguous-params/1.0.0/

I only updated the classifiers and the requirements but the rest is identical to your current master branch!

I figured I'd let you know :)

**Comment by frgfm** [comment]
Also made a conda release while I was at it: https://anaconda.org/frgfm/contiguous_params

**Comment by PhilJd** [comment]
Cool, thanks a lot! :) How about I add a note to the readme, pointing to the packages and stating that you're the maintainer for these?

**Comment by frgfm** [comment]
Oh well, currently on pypi there is no way people can know you're not the one who published it! On conda it's a different matter since it's on my personal channel. So I'd suggest you add references in installation instructions, and do as you please about mentioning, I really only published them, I really don't think it's worth mentioning :ok_hand: 

Besides, I'm not the maintainer, you are haha

**Comment by PhilJd** [comment]
Well, you're the maintainer of the PyPi releases, so I'd try to make sure to forward requests about updating the package on PyPi/Conda to you ;)
And as far as I've seen, at least on the pypi website for the package, there's an author (which lists me) and a pypi-maintainer tag (which lists you), so that's fine there.
