### ISSUE TITLE
How to handle the  parameter groups when defining the optimizer?

### ISSUE THREAD

**Issue by ownstyledu** [PhilJd/contiguous_pytorch_params#4]
Sometimes we define the optimizer using the dicts for parameters group instead of directly calling the parameters(), I just wonder how to handle this condition? For example,
`train_params = [{'params': self.net.get_train_params(), 'lr': cfg.lr}]` 
`self.optimizer = torch.optim.Adam(train_params, lr=cfg.lr, betas=(0.5, 0.999))`

Very much appreciate it.

**Comment by PhilJd** [comment]
Hi, thanks for the interest!
You would replace the parameters in the dict by the contiguous ones, i.e.:
```
params = self.net.get_train_params()
params = ContiguousParams(params)
train_params = [{'params': params.contiguous(), 'lr': cfg.lr}]
self.optimizer = torch.optim.Adam(train_params, lr=cfg.lr, betas=(0.5, 0.999))
```
Does that answer your question?

**Comment by ownstyledu** [comment]
Thanks for the quick reply XD. 【params】 in my program is a list that contains the parameter objects, which could directly apply to the opimizer in Pytorch, however, it seems this project does not support this format.

**Comment by PhilJd** [comment]
I'm not sure I understand what you mean by directly apply? The trick of the contiguous parameters is to change the parameter representation into a single buffer for the optimizer, so it's by design that there's on updates on the original parameter list ;)

**Comment by ownstyledu** [comment]
`.parameters()`returns a iterator for parameters, however, sometimes my program returns a python `list` containing parameters which is used as the  value of dict params, eg. 
`selected_params = [p for n, p in model.named_parameters() if [conditions] and p.requires_grad]`
`train_params = [{'params': selected_params, 'lr': cfg.lr}]`
`optimizer = torch.optim.Adam(train_params, lr=cfg.lr, betas=(0.5, 0.999))`
In this condition, the `opimizer` in pytorch still works well. I just wonder whether a python list containing parameters could be contiguoused in this condition? Do I make me understood this time, XD

**Comment by PhilJd** [comment]
Hi,
passing a list should work as well! Internally, the first thing the contiguous params class does is to convert the iterator to a list, so if you pass a list to the constructor, it just stays a list.
